export const countries = [
  "Nigeria",
  "Ghana",
  "South Africa",
  "Kenya",
  "Egypt",
  "Morocco",
  "United Kingdom",
  "United States",
  "Canada",
  "Ireland",
  "Germany",
  "France",
  "Netherlands",
  "Belgium",
  "Spain",
  "Portugal",
  "Italy",
  "Sweden",
  "Norway",
  "Denmark",
  "Switzerland",
  "Austria",
  "Poland",
  "Czech Republic",
  "Greece",
  "Turkey",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Israel",
  "India",
  "Pakistan",
  "Bangladesh",
  "China",
  "Japan",
  "South Korea",
  "Singapore",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Australia",
  "New Zealand",
  "Brazil",
  "Argentina",
  "Chile",
  "Mexico"
] as const;

export type Country = (typeof countries)[number];

export const statesByCountry: Record<Country, readonly string[]> = {
  Nigeria: [
    "Abia",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "FCT",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nasarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara"
  ],
  Ghana: ["Ashanti", "Bono", "Central", "Eastern", "Greater Accra", "Northern", "Oti", "Savannah", "Upper East", "Upper West", "Volta", "Western", "Western North"],
  "South Africa": ["Eastern Cape", "Free State", "Gauteng", "KwaZulu-Natal", "Limpopo", "Mpumalanga", "Northern Cape", "North West", "Western Cape"],
  Kenya: ["Baringo", "Busia", "Elgeyo-Marakwet", "Kajiado", "Kiambu", "Kilifi", "Kisumu", "Machakos", "Meru", "Mombasa", "Nairobi", "Nakuru", "Nyeri", "Uasin Gishu"],
  Egypt: ["Alexandria", "Aswan", "Asyut", "Beheira", "Cairo", "Dakahlia", "Gharbia", "Giza", "Luxor", "Minya", "Monufia", "Port Said", "Qalyubia", "Sharqia", "Sohag"],
  Morocco: ["Beni Mellal-Khenifra", "Casablanca-Settat", "Draa-Tafilalet", "Fes-Meknes", "Marrakesh-Safi", "Oriental", "Rabat-Sale-Kenitra", "Souss-Massa", "Tangier-Tetouan-Al Hoceima"],
  "United Kingdom": ["England", "Scotland", "Wales", "Northern Ireland"],
  "United States": ["Alabama", "California", "Florida", "Georgia", "Illinois", "Maryland", "Massachusetts", "New Jersey", "New York", "Ohio", "Pennsylvania", "Texas", "Virginia", "Washington"],
  Canada: ["Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Nova Scotia", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan"],
  Ireland: ["Carlow", "Cork", "Donegal", "Dublin", "Galway", "Kerry", "Kildare", "Limerick", "Mayo", "Meath", "Waterford", "Wexford"],
  Germany: ["Baden-Wurttemberg", "Bavaria", "Berlin", "Brandenburg", "Bremen", "Hamburg", "Hesse", "Lower Saxony", "North Rhine-Westphalia", "Saxony", "Schleswig-Holstein"],
  France: ["Auvergne-Rhone-Alpes", "Bourgogne-Franche-Comte", "Brittany", "Grand Est", "Hauts-de-France", "Ile-de-France", "Normandy", "Nouvelle-Aquitaine", "Occitanie", "Pays de la Loire", "Provence-Alpes-Cote d'Azur"],
  Netherlands: ["Drenthe", "Flevoland", "Friesland", "Gelderland", "Groningen", "Limburg", "North Brabant", "North Holland", "Overijssel", "South Holland", "Utrecht", "Zeeland"],
  Belgium: ["Antwerp", "Brussels-Capital", "East Flanders", "Flemish Brabant", "Hainaut", "Liege", "Limburg", "Luxembourg", "Namur", "Walloon Brabant", "West Flanders"],
  Spain: ["Andalusia", "Aragon", "Basque Country", "Canary Islands", "Castile and Leon", "Catalonia", "Galicia", "Madrid", "Murcia", "Valencian Community"],
  Portugal: ["Aveiro", "Braga", "Coimbra", "Faro", "Leiria", "Lisbon", "Madeira", "Porto", "Santarem", "Setubal"],
  Italy: ["Abruzzo", "Campania", "Emilia-Romagna", "Lazio", "Liguria", "Lombardy", "Piedmont", "Puglia", "Sardinia", "Sicily", "Tuscany", "Veneto"],
  Sweden: ["Blekinge", "Dalarna", "Halland", "Jonkoping", "Norrbotten", "Skane", "Stockholm", "Uppsala", "Varmland", "Vasterbotten", "Vastra Gotaland", "Orebro"],
  Norway: ["Agder", "Innlandet", "More og Romsdal", "Nordland", "Oslo", "Rogaland", "Troms", "Trondelag", "Vestfold", "Vestland", "Viken"],
  Denmark: ["Capital Region", "Central Denmark", "North Denmark", "Region Zealand", "Southern Denmark"],
  Switzerland: ["Aargau", "Basel-Landschaft", "Basel-Stadt", "Bern", "Geneva", "Lucerne", "St. Gallen", "Ticino", "Vaud", "Zurich"],
  Austria: ["Burgenland", "Carinthia", "Lower Austria", "Salzburg", "Styria", "Tyrol", "Upper Austria", "Vienna", "Vorarlberg"],
  Poland: ["Dolnoslaskie", "Kujawsko-Pomorskie", "Lodzkie", "Lubelskie", "Malopolskie", "Mazowieckie", "Podkarpackie", "Pomorskie", "Slaskie", "Wielkopolskie"],
  "Czech Republic": ["Central Bohemian", "Hradec Kralove", "Liberec", "Moravian-Silesian", "Olomouc", "Prague", "South Bohemian", "South Moravian", "Usti nad Labem", "Vysocina"],
  Greece: ["Attica", "Central Greece", "Central Macedonia", "Crete", "Epirus", "Peloponnese", "South Aegean", "Thessaly", "Western Greece"],
  Turkey: ["Adana", "Ankara", "Antalya", "Bursa", "Gaziantep", "Istanbul", "Izmir", "Konya", "Mersin", "Samsun"],
  "United Arab Emirates": ["Abu Dhabi", "Ajman", "Dubai", "Fujairah", "Ras Al Khaimah", "Sharjah", "Umm Al Quwain"],
  "Saudi Arabia": ["Asir", "Eastern Province", "Jazan", "Makkah", "Madinah", "Najran", "Qassim", "Riyadh", "Tabuk"],
  Qatar: ["Al Daayen", "Al Khor", "Al Rayyan", "Al Wakrah", "Doha", "Umm Salal"],
  Israel: ["Central", "Haifa", "Jerusalem", "Northern", "Southern", "Tel Aviv"],
  India: ["Andhra Pradesh", "Delhi", "Gujarat", "Karnataka", "Kerala", "Maharashtra", "Punjab", "Rajasthan", "Tamil Nadu", "Telangana", "Uttar Pradesh", "West Bengal"],
  Pakistan: ["Balochistan", "Islamabad Capital Territory", "Khyber Pakhtunkhwa", "Punjab", "Sindh"],
  Bangladesh: ["Barisal", "Chattogram", "Dhaka", "Khulna", "Mymensingh", "Rajshahi", "Rangpur", "Sylhet"],
  China: ["Anhui", "Beijing", "Chongqing", "Fujian", "Guangdong", "Hebei", "Henan", "Hubei", "Jiangsu", "Shandong", "Shanghai", "Sichuan", "Zhejiang"],
  Japan: ["Aichi", "Chiba", "Fukuoka", "Hokkaido", "Hyogo", "Kanagawa", "Kyoto", "Okinawa", "Osaka", "Saitama", "Tokyo"],
  "South Korea": ["Busan", "Daegu", "Daejeon", "Gangwon", "Gyeonggi", "Incheon", "Jeju", "North Chungcheong", "Seoul", "South Gyeongsang"],
  Singapore: ["Central Singapore", "North East", "North West", "South East", "South West"],
  Malaysia: ["Johor", "Kedah", "Kelantan", "Kuala Lumpur", "Malacca", "Negeri Sembilan", "Penang", "Perak", "Sabah", "Sarawak", "Selangor", "Terengganu"],
  Indonesia: ["Bali", "Banten", "Central Java", "East Java", "Jakarta", "South Sulawesi", "South Sumatra", "West Java", "Yogyakarta"],
  Philippines: ["Bicol", "Calabarzon", "Central Luzon", "Central Visayas", "Davao", "Ilocos", "Metro Manila", "Northern Mindanao", "Western Visayas"],
  Australia: ["Australian Capital Territory", "New South Wales", "Northern Territory", "Queensland", "South Australia", "Tasmania", "Victoria", "Western Australia"],
  "New Zealand": ["Auckland", "Bay of Plenty", "Canterbury", "Gisborne", "Hawke's Bay", "Otago", "Southland", "Taranaki", "Waikato", "Wellington"],
  Brazil: ["Bahia", "Ceara", "Distrito Federal", "Goias", "Minas Gerais", "Parana", "Pernambuco", "Rio de Janeiro", "Rio Grande do Sul", "Santa Catarina", "Sao Paulo"],
  Argentina: ["Buenos Aires", "Catamarca", "Cordoba", "Entre Rios", "Mendoza", "Neuquen", "Salta", "Santa Fe", "Tucuman"],
  Chile: ["Antofagasta", "Araucania", "Atacama", "Bio Bio", "Coquimbo", "Los Lagos", "Maule", "Metropolitana de Santiago", "Valparaiso"],
  Mexico: ["Baja California", "Chihuahua", "Guanajuato", "Jalisco", "Mexico City", "Nuevo Leon", "Oaxaca", "Puebla", "Queretaro", "Veracruz", "Yucatan"]
};
