export const nigerianStates = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara"
] as const;

export type NigerianState = (typeof nigerianStates)[number];

export const nigerianInstitutionsByState: Record<NigerianState, string[]> = {
  Abia: ["Abia State University", "Gregory University", "Michael Okpara University of Agriculture", "Abia State Polytechnic"],
  Adamawa: ["Adamawa State University", "American University of Nigeria", "Federal Polytechnic Mubi", "Modibbo Adama University"],
  "Akwa Ibom": ["Akwa Ibom State Polytechnic", "Akwa Ibom State University", "Obong University", "University of Uyo"],
  Anambra: ["Chukwuemeka Odumegwu Ojukwu University", "Federal Polytechnic Oko", "Madonna University Okija", "Nnamdi Azikiwe University"],
  Bauchi: ["Abubakar Tafawa Balewa University", "Abubakar Tatari Ali Polytechnic", "Federal Polytechnic Bauchi", "Sa'adu Zungur University"],
  Bayelsa: ["Bayelsa Medical University", "Federal University Otuoke", "Niger Delta University", "University of Africa Toru-Orua"],
  Benue: ["Benue State Polytechnic", "Benue State University", "Federal University of Health Sciences Otukpo", "Joseph Sarwuan Tarka University"],
  Borno: ["Borno State University", "Ramat Polytechnic", "University of Maiduguri"],
  "Cross River": ["Arthur Jarvis University", "University of Calabar", "University of Cross River State"],
  Delta: ["Delta State Polytechnic Otefe-Oghara", "Delta State University", "Federal University of Petroleum Resources Effurun", "University of Delta", "Dennis Osadebay University"],
  Ebonyi: ["Akanu Ibiam Federal Polytechnic", "Alex Ekwueme Federal University", "David Umahi Federal University of Health Sciences", "Ebonyi State University"],
  Edo: ["Ambrose Alli University", "Auchi Polytechnic", "Edo State Polytechnic", "Igbinedion University", "University of Benin"],
  Ekiti: ["Bamidele Olumilua University of Education", "Ekiti State University", "Federal Polytechnic Ado-Ekiti", "Federal University Oye-Ekiti"],
  Enugu: ["Caritas University", "Enugu State University of Science and Technology", "Institute of Management and Technology Enugu", "Godfrey Okoye University", "University of Nigeria Nsukka"],
  FCT: ["Baze University", "Nile University", "National Open University of Nigeria", "University of Abuja", "Veritas University"],
  Gombe: ["Federal University Kashere", "Gombe State Polytechnic", "Gombe State University"],
  Imo: ["Eastern Palm University", "Federal Polytechnic Nekede", "Federal University of Technology Owerri", "Imo State University"],
  Jigawa: ["Federal University Dutse", "Jigawa State Polytechnic", "Sule Lamido University"],
  Kaduna: ["Ahmadu Bello University", "Kaduna Polytechnic", "Kaduna State University", "Nigerian Defence Academy"],
  Kano: ["Aliko Dangote University of Science and Technology", "Bayero University Kano", "Kano State Polytechnic", "Northwest University Kano"],
  Katsina: ["Federal University Dutsin-Ma", "Hassan Usman Katsina Polytechnic", "Umaru Musa Yar'Adua University"],
  Kebbi: ["Federal University Birnin Kebbi", "Kebbi State University of Science and Technology", "Waziri Umaru Federal Polytechnic"],
  Kogi: ["Confluence University of Science and Technology", "Federal University Lokoja", "Kogi State Polytechnic", "Prince Abubakar Audu University"],
  Kwara: ["Federal Polytechnic Offa", "Kwara State Polytechnic", "Kwara State University", "University of Ilorin"],
  Lagos: ["Caleb University", "Lagos State University", "Lagos State University of Science and Technology", "University of Lagos", "Yaba College of Technology"],
  Nasarawa: ["Federal University of Lafia", "Isa Mustapha Agwai Polytechnic", "Nasarawa State University"],
  Niger: ["Federal University of Technology Minna", "Ibrahim Badamasi Babangida University", "Niger State Polytechnic"],
  Ogun: ["Federal Polytechnic Ilaro", "Moshood Abiola Polytechnic", "Olabisi Onabanjo University", "Tai Solarin University of Education", "Federal University of Agriculture Abeokuta"],
  Ondo: ["Adekunle Ajasin University", "Federal University of Technology Akure", "Rufus Giwa Polytechnic", "University of Medical Sciences Ondo"],
  Osun: ["Federal Polytechnic Ede", "Obafemi Awolowo University", "Osun State Polytechnic Iree", "Osun State University"],
  Oyo: ["Emmanuel Alayande University of Education", "Ladoke Akintola University of Technology", "The Polytechnic Ibadan", "University of Ibadan"],
  Plateau: ["Plateau State Polytechnic", "Plateau State University", "University of Jos"],
  Rivers: ["Captain Elechi Amadi Polytechnic", "Ignatius Ajuru University of Education", "PAMO University of Medical Sciences", "Rivers State University", "University of Port Harcourt"],
  Sokoto: ["Shehu Shagari University of Education", "Sokoto State University", "Umaru Ali Shinkafi Polytechnic", "Usmanu Danfodiyo University"],
  Taraba: ["Federal University Wukari", "Taraba State Polytechnic", "Taraba State University"],
  Yobe: ["Federal University Gashua", "Mai Idris Alooma Polytechnic", "Yobe State University"],
  Zamfara: ["Abdu Gusau Polytechnic", "Federal University Gusau", "Zamfara State University"]
};
