export const queryKeys = {
  adminDashboard: ['admin-dashboard'] as const,
  adminDashboardOverview: ['admin-dashboard-overview'] as const,
  adminContentReview: ['admin-content-review'] as const,
  adminBilling: ['admin-billing'] as const,
  adminNotifications: ['admin-notifications'] as const,
  adminLibrary: (section: string, filters: Record<string, unknown>) => ['admin-library', section, filters] as const,
  adminLibraryDetail: (section: string, materialId: string) => ['admin-library-detail', section, materialId] as const,
  adminLibrarySearch: (query: string) => ['admin-library-search', query] as const,
  adminPortalSearch: (query: string) => ['admin-portal-search', query] as const,
  studentPortalSearch: (query: string) => ['student-portal-search', query] as const,
  librarySearch: (audience: "admin" | "student", query: string) => ['library-search', audience, query] as const,
  adminMonthlyRegistrations: (year: number) => ['admin-monthly-registrations', year] as const,
  helarConnectQuestions: (filters: Record<string, unknown>) => ['helar-connect-questions', filters] as const,
  helarConnectUsers: (search: string) => ['helar-connect-users', search] as const,
  subjectSummaryModuleAdminEntries: (filters: Record<string, unknown>) => ['subject-summary-module-admin-entries', filters] as const,
  subjectSummaryModuleAdminFormOptions: (subjectId: string) => ['subject-summary-module-admin-form-options', subjectId] as const,
  subjectSummaryModuleAdminTopics: (params: Record<string, unknown>) => ['subject-summary-module-admin-topics', params] as const,
  subjectSummaryModuleStudentEntries: (params: Record<string, unknown>) => ['subject-summary-module-student-entries', params] as const,
  subjectSummaryModuleStudentSubjects: (params: Record<string, unknown>) => ['subject-summary-module-student-subjects', params] as const,
  subjectSummaryModuleStudentTopics: (params: Record<string, unknown>) => ['subject-summary-module-student-topics', params] as const,
  adminBarFinalExamQuestions: (filters: Record<string, unknown>) => ['admin-bar-final-exam-questions', filters] as const,
  adminBarFinalExamFormOptions: ['admin-bar-final-exam-form-options'] as const,
  adminBarFinalExamMcqQuestions: (filters: Record<string, unknown>) => ['admin-bar-final-exam-mcq-questions', filters] as const,
  adminBarFinalExamMcqFormOptions: ['admin-bar-final-exam-mcq-form-options'] as const,
  studentBarFinalExamSubjects: (search: string) => ['student-bar-final-exam-subjects', search] as const,
  studentBarFinalExamQuestions: (subjectId: string) => ['student-bar-final-exam-questions', subjectId] as const,
  studentBarFinalExamMcqSubjects: (search: string) => ['student-bar-final-exam-mcq-subjects', search] as const,
  studentBarFinalExamMcqQuestions: (subjectId: string) => ['student-bar-final-exam-mcq-questions', subjectId] as const,
  studentBarFinalExamMcqAttempt: (questionId: string) => ['student-bar-final-exam-mcq-attempt', questionId] as const,
  subjectSummaryAutocomplete: (query: string) => ['subject-summary-autocomplete', query] as const,
  subjectSummaryCaseDetail: (caseId: string) => ['subject-summary-case-detail', caseId] as const,
  subjectSummaryCases: (filters: Record<string, unknown>) => ['subject-summary-cases', filters] as const,
  subjectSummaryHierarchy: (params: Record<string, unknown>) => ['subject-summary-hierarchy', params] as const,
  subjectSummaryHierarchyCases: (topicId: string, params: Record<string, unknown>) => ['subject-summary-hierarchy-cases', topicId, params] as const,
  subjectSummaryHierarchyTopics: (subjectId: string, params: Record<string, unknown>) => ['subject-summary-hierarchy-topics', subjectId, params] as const,
  subjectSummaryPublishedAutocomplete: (query: string) => ['subject-summary-published-autocomplete', query] as const,
  subjectSummaryPublishedCases: (filters: Record<string, unknown>) => ['subject-summary-published-cases', filters] as const,
  subjectSummaryPublishedHierarchy: (params: Record<string, unknown>) => ['subject-summary-published-hierarchy', params] as const,
  subjectSummaryPublishedHierarchyCases: (topicId: string, params: Record<string, unknown>) => ['subject-summary-published-hierarchy-cases', topicId, params] as const,
  subjectSummaryPublishedHierarchyTopics: (subjectId: string, params: Record<string, unknown>) => ['subject-summary-published-hierarchy-topics', subjectId, params] as const,
  subjectSummaryReadingInsights: ['subject-summary-reading-insights'] as const,
  subjectSummarySubjects: (filters: Record<string, unknown>) => ['subject-summary-subjects', filters] as const,
  subjectSummaryTopics: (filters: Record<string, unknown>) => ['subject-summary-topics', filters] as const,
  adminUserDetail: (userId: string) => ['admin-user-detail', userId] as const,
  adminUsers: (filters: Record<string, unknown>) => ['admin-users', filters] as const,
  dashboard: ['dashboard'] as const,
  pricing: ['pricing'] as const,
  subscriptionPlans: ['subscription-plans'] as const,
  subscriptionSnapshot: ['subscription-snapshot'] as const,
  studentStudyBookmarks: (filters: Record<string, unknown>) => ['student-study-bookmarks', filters] as const,
  studentStudyCenter: ['student-study-center'] as const,
  studentStudyDownloads: (search: string) => ['student-study-downloads', search] as const,
  studentStudyNotes: (search: string) => ['student-study-notes', search] as const,
  studentStudyProgress: (contentKey: string) => ['student-study-progress', contentKey] as const,
  studentStudySearch: (query: string) => ['student-study-search', query] as const,
  adminCbts: (filters: Record<string, unknown>) => ['admin-cbts', filters] as const,
  adminCbtDetail: (cbtId: string) => ['admin-cbt-detail', cbtId] as const,
  adminCbtResults: (cbtId: string) => ['admin-cbt-results', cbtId] as const,
  adminQuestions: (filters: Record<string, unknown>) => ['admin-questions', filters] as const,
  adminQuestionDetail: (questionId: string) => ['admin-question-detail', questionId] as const,
  studentCbts: () => ['student-cbts'] as const,
  studentCbtDetail: (cbtId: string) => ['student-cbt-detail', cbtId] as const,
  studentCbtAttempt: (attemptId: string) => ['student-cbt-attempt', attemptId] as const,
  studentCbtResults: () => ['student-cbt-results'] as const,
  studentCbtAttemptResult: (attemptId: string) => ['student-cbt-attempt-result', attemptId] as const,
}
